FROM python:3.11.8-slim

WORKDIR /app

# Install system dependencies OpenCV versi py gak support opcv2
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    tesseract-ocr \
    tesseract-ocr-ind \
    tesseract-ocr-eng \
    libtesseract-dev \
 && rm -rf /var/lib/apt/lists/*


COPY . .

RUN pip install -r requirements.txt

CMD ["uvicorn", "main:app", "--port", "8000", "--host", "0.0.0.0"]